/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

/**
 *
 * @author kaito
 */
public class ListRoom extends javax.swing.JPanel {

    /**
     * Creates new form ListRoom
     */
    public ListRoom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        room2 = new swing.Room();
        room16 = new swing.Room();
        room6 = new swing.Room();
        room5 = new swing.Room();
        room4 = new swing.Room();
        room1 = new swing.Room();
        jLabel2 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        room18 = new swing.Room();
        room17 = new swing.Room();
        room11 = new swing.Room();
        room10 = new swing.Room();
        room9 = new swing.Room();
        room7 = new swing.Room();
        jLabel3 = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        room12 = new swing.Room();
        room19 = new swing.Room();
        room15 = new swing.Room();
        room14 = new swing.Room();
        room13 = new swing.Room();
        room3 = new swing.Room();
        jLabel4 = new javax.swing.JLabel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        room22 = new swing.Room();
        room25 = new swing.Room();
        room24 = new swing.Room();
        room23 = new swing.Room();
        room21 = new swing.Room();
        room20 = new swing.Room();
        jLabel5 = new javax.swing.JLabel();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        room28 = new swing.Room();
        room31 = new swing.Room();
        room30 = new swing.Room();
        room29 = new swing.Room();
        room27 = new swing.Room();
        room8 = new swing.Room();
        jLabel6 = new javax.swing.JLabel();
        jLayeredPane6 = new javax.swing.JLayeredPane();
        room33 = new swing.Room();
        room36 = new swing.Room();
        room35 = new swing.Room();
        room34 = new swing.Room();
        room32 = new swing.Room();
        room26 = new swing.Room();

        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("1ST FLOOR");

        jLayeredPane1.setLayout(new java.awt.GridLayout(1, 0, 10, 0));
        jLayeredPane1.add(room2);
        jLayeredPane1.add(room16);
        jLayeredPane1.add(room6);
        jLayeredPane1.add(room5);
        jLayeredPane1.add(room4);
        jLayeredPane1.add(room1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("2ND FLOOR");

        jLayeredPane2.setLayout(new java.awt.GridLayout(1, 0, 10, 0));
        jLayeredPane2.add(room18);
        jLayeredPane2.add(room17);
        jLayeredPane2.add(room11);
        jLayeredPane2.add(room10);
        jLayeredPane2.add(room9);
        jLayeredPane2.add(room7);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("3TH FLOOR");

        jLayeredPane3.setLayout(new java.awt.GridLayout(1, 0, 10, 0));
        jLayeredPane3.add(room12);
        jLayeredPane3.add(room19);
        jLayeredPane3.add(room15);
        jLayeredPane3.add(room14);
        jLayeredPane3.add(room13);
        jLayeredPane3.add(room3);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("4TH FLOOR");

        jLayeredPane4.setLayout(new java.awt.GridLayout(1, 0, 10, 0));
        jLayeredPane4.add(room22);
        jLayeredPane4.add(room25);
        jLayeredPane4.add(room24);
        jLayeredPane4.add(room23);
        jLayeredPane4.add(room21);
        jLayeredPane4.add(room20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("5TH FLOOR");

        jLayeredPane5.setLayout(new java.awt.GridLayout(1, 0, 10, 0));
        jLayeredPane5.add(room28);
        jLayeredPane5.add(room31);
        jLayeredPane5.add(room30);
        jLayeredPane5.add(room29);
        jLayeredPane5.add(room27);
        jLayeredPane5.add(room8);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("6TH FLOOR");

        jLayeredPane6.setLayout(new java.awt.GridLayout(1, 0, 10, 0));
        jLayeredPane6.add(room33);
        jLayeredPane6.add(room36);
        jLayeredPane6.add(room35);
        jLayeredPane6.add(room34);
        jLayeredPane6.add(room32);
        jLayeredPane6.add(room26);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1124, Short.MAX_VALUE)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLayeredPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel2.getAccessibleContext().setAccessibleName("2ND FLOOR");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLayeredPane jLayeredPane6;
    private swing.Room room1;
    private swing.Room room10;
    private swing.Room room11;
    private swing.Room room12;
    private swing.Room room13;
    private swing.Room room14;
    private swing.Room room15;
    private swing.Room room16;
    private swing.Room room17;
    private swing.Room room18;
    private swing.Room room19;
    private swing.Room room2;
    private swing.Room room20;
    private swing.Room room21;
    private swing.Room room22;
    private swing.Room room23;
    private swing.Room room24;
    private swing.Room room25;
    private swing.Room room26;
    private swing.Room room27;
    private swing.Room room28;
    private swing.Room room29;
    private swing.Room room3;
    private swing.Room room30;
    private swing.Room room31;
    private swing.Room room32;
    private swing.Room room33;
    private swing.Room room34;
    private swing.Room room35;
    private swing.Room room36;
    private swing.Room room4;
    private swing.Room room5;
    private swing.Room room6;
    private swing.Room room7;
    private swing.Room room8;
    private swing.Room room9;
    // End of variables declaration//GEN-END:variables
}
